jun950829/TRACKY-FE

.env
src/libs/apis/bizApi.ts
src/pages/About.tsx
vite.config.ts

api cors 세팅 및 예시 테스트
local 은 proxy로 세팅하였음

feat: api cors test 완료

---

src/constants/types.ts
src/libs/apis/carApi.ts
src/pages/car/CarRegister.tsx
src/pages/car/CarSection.tsx
src/pages/car/CarTable.tsx
src/pages/car/CarUpdateModal.tsx

feat: #2 차량 수정 & 차량 삭제 기능 추가

---

kill-port.js
package-lock.json
package.json
src/Routing.tsx
src/components/Header.tsx
src/components/PrivateRoute.tsx
src/components/custom/Btn.tsx
src/libs/utils/useLogout.ts
src/pages/Login.tsx
src/pages/car/CarUpdateModal.tsx
src/pages/emulator/Emulator.tsx
src/pages/rent/RentUpdateModal.tsx
src/stores/useAuthStore.ts
vite.config.ts

#14 WEB - feat: 로그인 및 로그아웃

---

src/components/custom/StatusBadge.stories.tsx
src/components/custom/StatusBadge.tsx
src/constants/status.ts
src/libs/apis/carApi.ts
src/libs/utils/getClassUtils.ts
src/pages/car/CarSearchLayer.tsx
src/pages/car/CarSection.tsx
src/pages/car/CarTable.tsx
src/pages/rent/RentSearchLayer.tsx
src/pages/rent/RentTable.tsx

차량 검색 필터링 기능 추가 / 등록 조회 페이지 리팩토링

---

src/libs/apis/carApi.ts
src/pages/car/CarRegister.tsx
src/pages/car/CarSearchLayer.tsx
src/pages/car/CarSection.tsx
src/pages/car/CarTable.tsx
src/pages/car/CarUpdateModal.tsx

#27
차량 생성 시 mdn 중복체크
차량 수정 시 mdn 고정

fix: 차량 등록 수정 / mdn 관련 세팅 변경

---

src/App.tsx
src/constants/types/types.ts
src/hooks/useSseEvents.ts
src/libs/utils/dashboardUtils.tsx
src/pages/car/CarRegister.tsx
src/pages/car/CarUpdateModal.tsx
src/pages/dashboard/DashBoardMain.tsx
src/pages/dashboard/RecentActivity.tsx
src/stores/useSseStore.ts
vite.config.ts

#44
sse 연결
차량 / 렌트 이벤트 처리
이벤트 별 ui 세팅

WEB - 대시보드 최근 기록 붙이기

---

src/libs/apis/rentsApi.ts
src/pages/rent/RentRegister.tsx
src/pages/rent/RentUpdateModal.tsx

#49 
예약 등록 수정 시 mdn, 예약 상태 select box 처리

WEB - 예약 등록 수정 시 mdn, 예약 상태 select box 처리

---

src/pages/dashboard/RecentActivity.tsx
src/pages/history/HistoryDrawer.tsx
src/pages/history/HistoryList.tsx
src/pages/history/HistoryMain.tsx

feat: 운행기록 ui 수정, 에뮬레이터 수정, dashboard 지도 ui 오류 수정

---

src/libs/apis/rentsApi.ts
src/pages/dashboard/RecentActivity.tsx
src/pages/history/HistoryDrawer.tsx
src/pages/history/HistoryList.tsx
src/pages/history/HistoryMain.tsx
src/pages/rent/RentRegister.tsx
src/pages/rent/RentUpdateModal.tsx

Develop to Main

---

src/pages/history/HistoryList.tsx
src/pages/history/HistorySearch.tsx

feat: 운행 정보 예약 list drawer ui 수정

---

src/pages/car/CarDetailModal.tsx
src/pages/car/CarRegister.tsx
src/pages/car/CarSearchLayer.tsx
src/pages/car/CarTable.tsx

#56 
1. 차량 등록시 MDN 10자리 이상 요구 멘트 추가
2. 차량 관리 페이지 사용목적 필터 삭제
3. 차량 상세 정보 불필요한 데이터 삭제
4. 차량 상세 정보에서 status 한글로 매핑

fix #56 차량관리 페이지 QA

---

src/pages/car/CarRegister.tsx
src/pages/rent/RentUpdateModal.tsx

#59
- ✅예약 정보 수정할 때 예약 상태를 전체로 해도 그대로 전체로 저장됩니다. (승준 - 진행 완 )
- ✅렌트 등록 할 때 대여기간 시간까지 똑같이 해도 등록이 됩니다. ( 승준 - 진행 완 - 프론트에서만 우선 막음 )
- ✅렌트 등록 할 때 반납시간을 대여시간 전으로 해도 등록이 됩니다. ( 승준 - 진행 완 - 프론트에서만 우선 막음 )
>

WEB - 렌트 수정 시 버그 해결

---

src/pages/car/CarRegister.tsx
src/pages/car/CarSearchLayer.tsx
src/pages/car/CarTable.tsx
src/pages/dashboard/KoreaMap.tsx
src/pages/history/HistoryCarList.tsx
src/pages/history/HistoryDetail.tsx
src/pages/history/HistoryRentList.tsx
src/pages/history/HistorySearch.tsx
src/pages/info/InfoResultSection.tsx
src/pages/info/InfoSearchSection.tsx
src/pages/rent/RentDetailModal.tsx
src/pages/rent/RentRegister.tsx
src/pages/rent/RentUpdateModal.tsx

fix - 세부 디테일들 수정

---

src/libs/utils/reservationUtils.ts
src/pages/dashboard/components/ReservationCard.tsx

feat: dashboard-rent list 수정

---

src/pages/rent/RentRegister.tsx

대여 등록 전화번호 형식 수정

---

src/components/routing/Routing.tsx
src/libs/apis/signup.ts
src/pages/Login.tsx
src/pages/signup/SignupForm.tsx
src/pages/signup/SignupMain.tsx
src/pages/signup/SignupModal.tsx

WEB - 회원가입 페이지

---

src/App.tsx
src/components/Sidebar.tsx

feat: sidebar - responsive

---

src/App.tsx
src/components/Sidebar.tsx

Reverts jun950829/TRACKY-FE#76

Revert "feat: sidebar - responsive"

---

src/pages/Login.tsx

#89 
- Login 페이지
- 공지사항 출력
- 스크롤
- 잘 봐주세요!

WEB - Login 페이지 Notice 리스트 출력

---

src/pages/admin/notice/NoticeSection.tsx
src/pages/car/CarSection.tsx
src/pages/car/CarTable.tsx
src/pages/dashboard/DashBoardMain.tsx
src/pages/dashboard/DashboardLayout.tsx
src/pages/rent/RentSearchLayer.tsx
src/pages/rent/RentSection.tsx
src/pages/rent/RentTable.tsx
src/pages/rent/register/RentRegister.tsx

#97
- 대시보드, 차량, 렌트 ui layer 조정 및 table 수정
- pagination naming error fix

WEB - Fix/layer fix

---

src/libs/utils/getClassUtils.ts

status lowercase 처리

---

src/libs/apis/driveApi.ts
src/pages/dashboard/DashBoardMain.tsx
src/pages/dashboard/components/ReturnedStatus.tsx
src/pages/history/HistoryCarList.tsx
src/pages/history/HistorySearch.tsx
src/pages/history/HistorySection.tsx
src/pages/history/HistoryTable.tsx
src/stores/useDriveListStore.ts

#94
날짜, 사용자 검색 상태관리 처리 +pagination
>

WEB - 운행기록 주행리스트

---

src/constants/types/historyTypes.ts
src/libs/apis/driveApi.ts
src/libs/utils/getClassUtils.ts
src/pages/dashboard/DashBoardMain.tsx
src/pages/dashboard/components/ReturnedStatus.tsx
src/pages/history/HistoryCarList.tsx
src/pages/history/HistorySearch.tsx
src/pages/history/HistorySection.tsx
src/pages/history/HistoryTable.tsx
src/pages/history/detail/HistoryDetailPage.tsx
src/stores/useDriveListStore.ts

WEB - 운행 상세 페이지 ui 와 api 싱크

---

package.json
src/components/ui/separator.tsx
src/constants/types/historyTypes.ts
src/libs/apis/driveApi.ts
src/libs/utils/getClassUtils.ts
src/libs/utils/historyUtils.ts
src/pages/dashboard/DashBoardMain.tsx
src/pages/dashboard/DashboardLayout.tsx
src/pages/dashboard/components/ReturnedStatus.tsx
src/pages/history/HistoryCarList.tsx
src/pages/history/HistorySearch.tsx
src/pages/history/HistorySection.tsx
src/pages/history/HistoryTable.tsx
src/pages/history/detail/HistoryDetailPage.tsx
src/pages/history/detail/HistoryMap.tsx
src/stores/useDriveListStore.ts

운행 기록 & 대시보드 ui 간단 수정 ( 아래부터 순서대로 여기까지 pr )

---

src/pages/history/HistorySection.tsx
src/pages/history/HistoryTable.tsx
src/pages/history/detail/HistoryDetailPage.tsx

WEB - simple ui fix

---

src/hooks/useSseEvents.ts
src/libs/apis/carApi.ts
src/libs/utils/getClassUtils.ts
src/libs/utils/gpsBuffer.ts
src/pages/Home.tsx
src/pages/admin/notice/NoticeTable.tsx
src/pages/car/CarSection.tsx
src/pages/car/CarTable.tsx
src/pages/car/CarUpdateModal.tsx
src/pages/car/register/CarRegister.tsx
src/pages/emulator/Emulator.tsx
src/pages/etc/notice/NoticeSection.tsx
src/pages/etc/notice/NoticeTable.tsx
src/pages/history/HistoryTable.tsx
src/pages/rent/RentDetailModal.tsx
src/pages/rent/RentTable.tsx

#109
차량 soft delete 추가 및 update modal logic fix & 불필요한 log 제거
>

WEB - 차량 soft delete 추가 및 update modal logic fix & 불필요한 log 제거

---

src/constants/datas/options.ts
src/pages/car/CarSearchLayer.tsx
src/pages/rent/RentSearchLayer.tsx
src/stores/useCarListStore.ts

feat: rent table 총 개수 설정

---

package.json
src/components/address/AddressSearch.tsx
src/components/ui/scroll-area.tsx
src/hooks/useAddressSearch.ts
src/libs/apis/addressApi.ts
src/libs/utils.ts
src/libs/utils/utils.ts
src/pages/rent/register/RentRegister.tsx

feat: rent address 추가

---

src/pages/rent/RentDetailModal.tsx

> ex) #116 
> 렌트 디테일 modal 수정
>

WEB - 렌트 디테일 modal 수정

---

src/constants/types/reservation.ts
src/constants/types/types.ts
src/libs/apis/dashboardApi.ts
src/libs/utils/dashboardUtils.tsx
src/libs/utils/reservationUtils.ts
src/pages/dashboard/DashBoardMain.tsx
src/pages/dashboard/KoreaMap.tsx
src/pages/dashboard/components/ReturnedStatus.tsx
src/pages/rent/register/RentRegister.tsx

대시보드 대공사ing

---

src/libs/apis/carApi.ts
src/libs/apis/driveApi.ts
src/pages/car/CarSearchLayer.tsx
src/pages/car/CarSection.tsx
src/pages/history/HistoryTable.tsx

WEB - Excel 추출 기능 추가

---

src/pages/history/HistoryCarList.tsx
src/stores/useDriveListStore.ts

WEB - 운행기록 중복 호출 해결

---

src/pages/rent/RentUpdateModal.tsx
src/pages/rent/register/RentRegister.tsx

> ex) #105 
> WEB - 예약 시, 겹치는 예약 시간 공지
>

WEB - 예약 시, 겹치는 예약 시간 공지

---

src/pages/admin/notice/NoticeSearchLayer.tsx
src/pages/etc/notice/NoticeSearchLayer.tsx

WEB - 공지사항 초기화 버튼 수정

---

src/pages/admin/member/ApprovalTable.tsx
src/pages/admin/member/MemberTable.tsx
src/pages/admin/notice/NoticeTable.tsx
src/pages/car/CarTable.tsx
src/pages/etc/notice/NoticeTable.tsx
src/pages/history/HistoryTable.tsx
src/pages/rent/RentTable.tsx

#129 
- 모든 테이블 컴포넌트에서 헤더와 본문 컬럼의 수직 정렬 문제 해결
- 
- tableLayout: 'fixed' 스타일과 동일한 너비 적용으로 일관된 레이아웃 구현
- 스크롤 시 테이블 헤더 고정 및 본문 영역 스크롤 가능하도록 구조 개선
- 잘 봐주세요.

WEB - refactor #129 테이블 컴포넌트의 헤더와 본문 컬럼 정렬 수정

---

src/constants/types/rentTypes.ts
src/pages/rent/RentDetailModal.tsx
src/pages/rent/RentUpdateModal.tsx
src/pages/rent/register/RentRegister.tsx
src/pages/rent/rentValidator.ts

렌트 등록 및 수정 시 차량 번호와 함께 CarStatus 내려오도록 수정
또한 대여 시작 날짜와 종료 날짜의 차이가 30분 이상이어야 등록 및 수정 가능하도록 validation 추가했습니다
기존에 있던 setIsTimeError 관련 validation은 새로운 로직과 합쳐졌습니다
>

렌트 등록, 수정에 차량 상태값 내려오도록 수정, 날짜 관련 validation 추가

---

src/components/address/AddressSearch.tsx
src/components/ui/alert.tsx
src/constants/types/types.ts
src/libs/apis/rentsApi.ts
src/libs/utils/utils.ts
src/pages/rent/register/RentRegister.tsx
src/pages/rent/register/Step1Form.tsx
src/pages/rent/register/Step2Form.tsx
src/pages/rent/register/Step3Form.tsx
src/stores/rentStore.ts

WEB - rent 리뉴얼 고려중 / merge 절대 금지

---

src/components/ui/separator.tsx
src/constants/types/types.ts
src/pages/dashboard/DashBoardMain.tsx
src/pages/dashboard/components/MonthlyStats.tsx

대시보드 통계 데이터 부분 목 데이터 제거 및 실제 데이터로 생성하였습니다.

feat : 대시보드 통계 부분 목 데이터 제거 및 실제 데이터로 생성

---

src/constants/types/rentTypes.ts
src/constants/types/types.ts
src/pages/rent/RentUpdateModal.tsx

렌트 정보 수정 - mdn 목록에 해당 차량의 CarStatus가 함께 내려오도록 추가 및 StatusBadge 요소로 수정

fix 렌트 정보 수정 - mdnStatus.status를 StatusBadge 요소로 변경

---

src/constants/mocks/carStatisticMockData.ts
src/constants/types/types.ts
src/libs/apis/statisticApi.ts
src/libs/utils/dashboardUtils.tsx
src/pages/admin/statistic/AdminStatisticSection.tsx
src/pages/rent/RentUpdateModal.tsx
src/pages/rent/register/RentRegister.tsx
src/pages/statistic/car/StatisticCarTable.tsx
src/pages/statistic/daily/DailyCards.tsx
src/pages/statistic/daily/DailyCharts.tsx
src/pages/statistic/monthly/MonthlyCards.tsx
src/pages/statistic/monthly/MonthlyCharts.tsx

업체별 통계, 차량 상세 통계 백엔드와 연결

---

src/pages/admin/statistic/AdminStatisticSection.tsx
src/pages/rent/register/RentRegister.tsx

AdminStatisticSection에 중복된 useEffect가 있어 삭제했습니다

Hotfix AdminStatisticSection useEffect 중복 코드 삭제

---

src/pages/statistic/monthly/MonthlyCards.tsx

fix 통계 페이지 텍스트 수정

---

src/constants/types/reservation.ts
src/libs/apis/dashboardApi.ts
src/pages/dashboard/DashBoardMain.tsx
src/pages/dashboard/components/ReturnedStatus.tsx

대시보드 미반납 현황 반납처리 버튼 추가

---

src/libs/apis/driveApi.ts
src/pages/dashboard/KoreaMap.tsx

대시보드 차량 위치 지도 응답에 정수 대신 mdn이 내려오도록 변경

대시보드 차량 위치 지도 응답에 정수 대신 mdn이 내려오도록 변경
